//LOCALHOST
### Get all contacts
GET http://localhost:3000/contacts

### Get Contact Id
GET http://localhost:3000/contacts/67cb3491bd2e2ab0da31919e


### Create Contact
POST  http://localhost:3000/contacts http/1.1
Content-Type: application/json

{
    "firstName":"Ashley",
    "lastName":"Beaver",
    "email":"ahsleybeaver@gmail.com",
    "favoriteColor":"Green",
    "birthday":"4/1/2000"
}

### PUT Contact
PUT http://localHost:3000/contacts/67d30efee709785439aced2c HTTP/1.1
content-Type: application/json

{
    "firstName":"Ashely",
    "lastName":"Beaver",
    "email":"ashleyBeaver@outlook.com",
    "favoriteColor":"blue",
    "birthday":"3/11/2000"
}

### Delete Contact
DELETE http://localhost:3000/contacts/67d31099e709785439aced2d